variables:
  QA_SERVER: 15.207.94.37
  PROD_SERVER: 3.108.213.299
deploy_staging:
  before_script:
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY_STG"
    - echo "$SSH_PRIVATE_KEY_STG" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "staging run"
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh -o StrictHostKeyChecking=no ubuntu@$QA_SERVER "cd 10xtd/workbench-live/; git checkout develop; git pull origin develop; sudo docker-compose stop -t 1; sudo docker-compose rm -f; sudo docker-compose up --build -d"
  only:
    - develop
deploy_production:
  before_script:
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY_PROD"
    - echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "production run"
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh -o StrictHostKeyChecking=no ubuntu@$PROD_SERVER "cd 10xtd/workbench-live/; git checkout main; git pull origin main; sudo docker-compose stop -t 1; sudo docker-compose rm -f; sudo docker-compose up --build -d"
  only:
    - main
